// vue-tooltip/src/components/Tooltip.vue
<script setup lang="ts">
import { TooltipProvider } from "@milkdown/kit/plugin/tooltip";
import { toggleStrongCommand } from '@milkdown/kit/preset/commonmark';
import { callCommand } from '@milkdown/kit/utils';
import { useInstance } from '@milkdown/vue';
import { usePluginViewContext } from '@prosemirror-adapter/vue';
import { onMounted, onUnmounted, ref, VNodeRef, watch } from 'vue';

const { view, prevState } = usePluginViewContext()
const [loading, get] = useInstance()

const divRef = ref<VNodeRef>();

let tooltipProvider: TooltipProvider;

onMounted(() => {
  tooltipProvider = new TooltipProvider({
    content: divRef.value as any,
  })

  tooltipProvider.update(view.value, prevState.value)
})

watch(
  [view, prevState],
  () => {
    tooltipProvider?.update(view.value, prevState.value)
  }
)

onUnmounted(() => {
  tooltipProvider.destroy()
})

const toggleBold = (e: Event) => {
  if (loading.value) return;

  e.preventDefault()

  get()!.action(callCommand(toggleStrongCommand.key))
}

</script>

<template>
  <div class="absolute data-[show=false]:hidden" ref="divRef">
    <button
      class="text-gray-600 bg-slate-200 px-2 py-1 rounded-lg hover:bg-slate-300 border hover:text-gray-900"
      @mousedown="toggleBold"
    >
      Bold
    </button>
  </div>
</template>

// react-tooltip/components/Tooltip.tsx
import { Ctx } from "@milkdown/kit/ctx"
import { tooltipFactory, TooltipProvider } from "@milkdown/kit/plugin/tooltip"
import { toggleStrongCommand } from "@milkdown/kit/preset/commonmark"
import { useInstance } from '@milkdown/react'
import { usePluginViewContext } from "@prosemirror-adapter/react"
import { useCallback, useEffect, useRef } from "react"
import { callCommand } from "@milkdown/kit/utils"

export const tooltip = tooltipFactory('Text');

export const TooltipView = () => {
    const ref = useRef<HTMLDivElement>(null)
    const tooltipProvider = useRef<TooltipProvider>()

    const { view, prevState } = usePluginViewContext()
    const [loading, get] = useInstance()
    const action = useCallback((fn: (ctx: Ctx) => void) => {
        if (loading) return;
        get().action(fn)
    }, [loading])

    useEffect(() => {
        const div = ref.current
        if (loading || !div) {
            return;
        }
        tooltipProvider.current = new TooltipProvider({
            content: div,
        })

        return () => {
            tooltipProvider.current?.destroy()
        }
    }, [loading])

    useEffect(() => {
        tooltipProvider.current?.update(view, prevState)
    })

    return (
          <div className="absolute data-[show=false]:hidden" ref={ref}>
              <button
                  className="text-gray-600 bg-slate-200 px-2 py-1 rounded-lg hover:bg-slate-300 border hover:text-gray-900"
                  onMouseDown={(e) => {
                      // Use `onMouseDown` with `preventDefault` to prevent the editor from losing focus.
                      e.preventDefault()

                      action(callCommand(toggleStrongCommand.key))
                  }}
              >
                  Bold
              </button>
          </div>
    )
}
